apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: valheim
  namespace: games
spec:
  selector:
    matchLabels:
      app: valheim
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: valheim
    spec:
      hostNetwork: true
      containers:
      - name: valheim
        image: lloesche/valheim-server
        imagePullPolicy: Always
        ports:
        - containerPort: 2456
          protocol: UDP
        - containerPort: 2457
          protocol: UDP
        env:
        - name: WORLD_NAME
          value: "I'm a lumberjack and I'm OK"
        - name: SERVER_NAME
          value: "tinker.haus"
        - name: SERVER_PASS
          value: "%%VALHEIM_PASS%%"
        - name: SERVER_PUBLIC
          value: "false"
        - name: TZ
          value: "Europe/Bucharest"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: server
            mountPath: /opt/valheim
      volumes:
        - name: config
          hostPath:
            path: /servers/valheim/config
            type: DirectoryOrCreate
        - name: server
          hostPath:
            path: /servers/valheim/server
            type: DirectoryOrCreate
