apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valheim-hh
  namespace: games
spec:
  serviceName: valheim-best-seed
  selector:
    matchLabels:
      app: valheim-hh
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: valheim-hh
    spec:
      hostNetwork: true
      containers:
      - name: valheim-hh
        image: docker-cache.tinker.haus/lloesche/valheim-server
        ports:
        - name: status
          containerPort: 12458
          protocol: TCP
        - name: game
          containerPort: 12456
          protocol: UDP
        - name: query
          containerPort: 12457
          protocol: UDP
        env:
        - name: SERVER_NAME
          value: "OmicronPersei8"
        - name: SERVER_PORT
          value: "12456"
        - name: WORLD_NAME
          value: "OmicronPersei8"
        - name: SERVER_PASS
          valueFrom:
           secretKeyRef:
            name: valheim-secret
            key: server-pass
        - name: SERVER_PUBLIC
          value: "false"
        - name: TZ
          value: "Europe/Bucharest"
        - name: BACKUPS_MAX_AGE
          value: "14"
        - name: STATUS_HTTP
          value: "true"
        - name: STATUS_HTTP_PORT
          value: "12458"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: server
            mountPath: /opt/valheim
      volumes:
        - name: config
          hostPath:
            path: /srv/games/valheim-hh/config
            type: DirectoryOrCreate
        - name: server
          hostPath:
            path: /srv/games/valheim-hh/server
            type: DirectoryOrCreate
