apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: valheim-hh
  namespace: games
spec:
  selector:
    matchLabels:
      app: valheim-hh
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: valheim-hh
    spec:
      hostNetwork: true
      containers:
      - name: valheim-hh
        image: docker-cache.tinker.haus/lloesche/valheim-server
        imagePullPolicy: Always
        ports:
        - containerPort: 2456
          protocol: UDP
        - containerPort: 2457
          protocol: UDP
        - containerPort: 2458
          protocol: UDP
        env:
        - name: WORLD_NAME
          value: "OmicronPersei8"
        - name: SERVER_NAME
          value: "OmicronPersei8"
        - name: SERVER_PASS
          value: "%%VALHEIM_PASS%%"
        - name: SERVER_PUBLIC
          value: "true"
        - name: SERVER_PORT
          value: "2456"
        - name: TZ
          value: "Europe/Bucharest"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: server
            mountPath: /opt/valheim
      volumes:
        - name: config
          hostPath:
            path: /var/srv/games/valheim-hh/config
            type: DirectoryOrCreate
        - name: server
          hostPath:
            path: /var/srv/games/valheim-hh/server
            type: DirectoryOrCreate
