apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valheim-prythian
  namespace: games
spec:
  serviceName: valheim-best-seed
  selector:
    matchLabels:
      app: valheim-prythian
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: valheim-prythian
    spec:
      hostNetwork: true
      containers:
      - name: valheim-prythian
        image: docker-cache.tinker.haus/lloesche/valheim-server
        ports:
        - name: status
          containerPort: 52458
          protocol: TCP
        - name: gameport
          containerPort: 52456
          protocol: UDP
        - name: queryport
          containerPort: 52457
          protocol: UDP
        env:
        - name: SERVER_NAME
          value: "Prythian"
        - name: SERVER_PORT
          value: "52456"
        - name: WORLD_NAME
          value: "Prythian"
        - name: SERVER_PASS
          value: ""
        - name: SERVER_PUBLIC
          value: "false"
        - name: TZ
          value: "Europe/Bucharest"
        - name: BACKUPS_MAX_AGE
          value: "14"
        - name: STATUS_HTTP
          value: "true"
        - name: STATUS_HTTP_PORT
          value: "52458"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: server
            mountPath: /opt/valheim
      volumes:
        - name: config
          hostPath:
            path: /srv/games/valheim-prythian/config
            type: DirectoryOrCreate
        - name: server
          hostPath:
            path: /srv/games/valheim-prythian/server
            type: DirectoryOrCreate
