apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: v2.8.1
    dashboard:
      enabled: true
    logs:
      access:
        enabled: true
    metrics:
      influxdb:
        address: influxdb.tinker.haus:8089
        protocol: udp
    env:
      - name: CF_API_EMAIL_FILE
        value: "/cloudflare/user"
      - name: CF_API_KEY_FILE
        value: "/cloudflare/key"
    additionalArguments:
      - "--certificatesResolvers.le.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.le.acme.email=alex.sever.h@gmail.com"
      - "--certificatesResolvers.le.acme.storage=/data/acme.json"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ports:
      transmissiontcp:
        port: 51413
        exposedPort: 51413
        protocol: TCP
      influxdb:
        port: 8086
        exposedPort: 8086
        protocol: TCP
      influxdbudp:
        port: 8089
        exposedPort: 8089
        protocol: UDP
      websecure:
        tls:
          certResolver: le
          domains:
            - main: "tinker.haus"
              sans:
              - "*.tinker.haus"
    logs:
      general:
        level: DEBUG
    volumes:
      - name: cloudflare-secret
        mountPath: "/cloudflare"
        type: secret
    persistence:
      enabled: true
      name: traefik-data
      
---
# dashboard.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: kube-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`traefik.tinker.haus`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
        - name: default-redirect-to-https@kubernetescrd
