apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: homeautomation
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
          protocol: TCP
        - containerPort: 8089
          protocol: UDP
        volumeMounts:
          - name: influxdb2
            mountPath: /var/lib/influxdb2
      volumes:
        - name: influxdb2
          hostPath:
            path: /var/srv/homeautomation/influxdb2
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: homeautomation
spec:
  ports:
  - name: "influxdbtcp"
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: "influxdbudp"
    port: 8089
    protocol: UDP
    targetPort: 8089
  type: NodePort
  selector:
    app: influxdb

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: influxdb
  namespace: homeautomation
spec:
  entryPoints:
    - influxdb
  routes:
  - match: HostSNI(`*`)
    services:
    - name: influxdb
      port: 8086
      terminationDelay: 4000

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: ingressrouteudpinfluxdb
  namespace: homeautomation
spec:
  entryPoints:
    - influxdbudp
  routes:
  -  services:
     - name: influxdb
       port: 8089



---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb-websecure
  namespace: homeautomation
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`influxdb.tinker.haus`)
      kind: Rule
      services:
        - name: influxdb
          port: 8086
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
  tls:
    certResolver: myresolver
    domains:
    - main: "tinker.haus"
      sans:
      - "*.tinker.haus"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb-web
  namespace: homeautomation
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`influxdb.tinker.haus`)
      kind: Rule
      services:
        - name: influxdb
          port: 8086
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
        - name: default-redirect-to-https@kubernetescrd
