apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: homeautomation
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: docker-cache.tinker.haus/library/postgres:latest
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD_FILE
          value: /var/lib/postgresql/password
        ports:
        - containerPort: 8080
        - containerPort: 5432
        volumeMounts:
          - name: db
            mountPath: /var/lib/postgresql/data
          - name: password
            mountPath: /var/lib/postgresql/password
      volumes:
        - name: db
          hostPath:
            path: /var/srv/homeautomation/postgresql/data
            type: DirectoryOrCreate
        - name: password
          hostPath:
            path: /var/srv/homeautomation/postgresql/password
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: homeautomation
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: "tcp-port"
  - port: 5432
    protocol: TCP
    targetPort: 5432
    name: "some-other-port"
  type: NodePort
  selector:
    app: postgresql
