apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: homeautomation
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: docker-cache.tinker.haus/grafana/grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: varlibgrafana
            mountPath: /var/lib/grafana
        env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
      volumes:
        - name: varlibgrafana
          hostPath:
            path: /var/srv/homeautomation/grafana/lib
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: homeautomation
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: NodePort
  selector:
    app: grafana
    
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: homeautomation
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`grafana.tinker.haus`)
      kind: Rule
      services:
        - name: grafana
          port: 80

