apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
  namespace: homeautomation
spec:
  serviceName: zigbee2mqtt
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
      - name: zigbee2mqtt
        image: docker-cache.tinker.haus/koenkk/zigbee2mqtt
        imagePullPolicy: Always
        ports:
        - name: webui
          containerPort: 8123
        env:
          - name: TZ
            value: "Europe/Bucharest"
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_RAW"]
        volumeMounts:
          - name: data
            mountPath: /app/data
          - name: cp210x
            mountPath: /dev/cp210x
      volumes:
        - name: data
          hostPath:
            path: /var/srv/homeautomation/zigbee2mqtt/data
            type: DirectoryOrCreate
        - name: cp210x
          hostPath:
            path: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_9a073488b729ec11a6edbd9c40c9ce8d-if00-port0 #TODO: This better
            type: CharDevice

---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: homeautomation
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    app: zigbee2mqtt

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zigbee2mqtt
  namespace: homeautomation
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`zigbee2mqtt.tinker.haus`)
      kind: Rule
      services:
        - name: zigbee2mqtt
          port: 80

