apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: homeautomation
spec:
  selector:
    matchLabels:
      app: mealie
  replicas: 1
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: docker-cache.tinker.haus/hkotel/mealie
        imagePullPolicy: Always
        env:
          - name: ALLOW_SIGNUP
            value: "true"
          - name: TZ
            value: "Europe/Bucharest"
          - name: BASE_URL
            value: "https://mealie.tinker.haus"
        ports:
          - containerPort: 9000
        volumeMounts:
          - name: data
            mountPath: /app/data
      volumes:
        - name: data
          hostPath:
            path: /var/srv/homeautomation/mealie/app/data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: homeautomation
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  type: NodePort
  selector:
    app: mealie

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie
  namespace: homeautomation
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`mealie.tinker.haus`)
      kind: Rule
      services:
        - name: mealie
          port: 80
