apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  namespace: homeautomation
spec:
  selector:
    matchLabels:
      app: nodered
  replicas: 1
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: docker-cache.tinker.haus/nodered/node-red
        imagePullPolicy: Always
        ports:
        - containerPort: 1880
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /var/srv/homeautomation/nodered
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: homeautomation
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1880
  type: NodePort
  selector:
    app: nodered

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nodered
  namespace: homeautomation
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`nodered.tinker.haus`)
      kind: Rule
      services:
        - name: nodered
          port: 80
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
        - name: default-redirect-to-https@kubernetescrd
