apiVersion: apps/v1
kind: Deployment
metadata:
  name: almond
  namespace: homeautomation
spec:
  selector:
    matchLabels:
      app: almond
  replicas: 1
  template:
    metadata:
      labels:
        app: almond
    spec:
      containers:
      - name: almond
        image: stanfordoval/almond-server:latest-portable
        imagePullPolicy: Always
        ports:
        - name: webui
          containerPort: 3000
        volumeMounts:
          - name: varlib
            mountPath: /var/lib/almond-server
#        livenessProbe:
#          httpGet:
#            path: /
#            port: webui
#          initialDelaySeconds: 30
#          periodSeconds: 3
      volumes:
        - name: varlib
          hostPath:
            path: /servers/almond/varlib
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: almond
  namespace: homeautomation
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: NodePort
  selector:
    app: almond
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: almond
  namespace: homeautomation
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`almond.tinker.haus`)
      kind: Rule
      services:
        - name: almond
          port: 80
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
  tls:
    certResolver: myresolver
    domains:
    - main: "tinker.haus"
      sans:
      - "*.tinker.haus"
