apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  namespace: homeautomation
spec:
  selector:
    matchLabels:
      app: esphome
  replicas: 1
  template:
    metadata:
      labels:
        app: esphome
    spec:
      containers:
      - name: esphome
        image: ghcr.io/esphome/esphome
         # imagePullPolicy: Always
        ports:
        - containerPort: 6052
        env:
            - name: TZ
              value: "Europe/Bucharest"
        volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          hostPath:
            path: /srv/homeautomation/esphome
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: esphome
  namespace: homeautomation
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6052
  type: NodePort
  selector:
    app: esphome

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: esphome
  namespace: homeautomation
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`esphome.tinker.haus`)
      kind: Rule
      services:
        - name: esphome
          port: 80

