apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeautomation
spec:
  selector:
    matchLabels:
      app: homeassistant
  replicas: 1
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        #image: docker-cache.tinker.haus/homeassistant/home-assistant:latest
        image: registry.tinker.haus/homeassistant:latest
         # imagePullPolicy: Always
        ports:
        - name: webui
          containerPort: 8123
        env:
          - name: PYTHONPATH
            value: "/config/custom_components"
        livenessProbe:
          httpGet:
            path: /
            port: webui
          initialDelaySeconds: 2160 # 30 minutes
          periodSeconds: 60
          timeoutSeconds: 15
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_RAW"]
        volumeMounts:
          - name: config
            mountPath: /config

      - name: whisper # speech-to-text
        image: docker-cache.tinker.haus/rhasspy/wyoming-whisper:latest
        args: ["--mode=medium-int8", "--language=en", "--beam-size=2"]
         # imagePullPolicy: Always
        ports:
        - name: whisper
          containerPort: 10300
        env:
          - name: TZ
            value: "Europe/Bucharest"
        volumeMounts:
          - name: whisper-data
            mountPath: /data

      - name: piper # text-to-speech
        image: docker-cache.tinker.haus/rhasspy/wyoming-piper:latest
        args: ["--voice=en-us-libritts-high"]
         # imagePullPolicy: Always
        ports:
        - name: piper
          containerPort: 10200
        env:
          - name: TZ
            value: "Europe/Bucharest"
        volumeMounts:
          - name: piper-data
            mountPath: /data

      - name: openwakeword
        image: docker-cache.tinker.haus/rhasspy/wyoming-openwakeword:latest
        args: 
#          - --preload-model='ok_nabu'
          - --custom-model-dir=/custom
#          - --uri='tcp://0.0.0.0:10400'
         # imagePullPolicy: Always
        ports:
        - name: openwakeword
          containerPort: 10400
        env:
          - name: TZ
            value: "Europe/Bucharest"
        volumeMounts:
          - name: openwakeword-data
            mountPath: /data

      volumes:
        - name: config
          hostPath:
            path: /srv/homeautomation/haas/config
            type: DirectoryOrCreate
        - name: whisper-data
          hostPath:
            path: /srv/homeautomation/haas/whisper-data
            type: DirectoryOrCreate
        - name: piper-data
          hostPath:
            path: /srv/homeautomation/haas/piper-data
            type: DirectoryOrCreate
        - name: openwakeword-data
          hostPath:
            path: /srv/homeautomation/haas/openwakeword-data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeautomation
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8123
  type: NodePort
  selector:
    app: homeassistant

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: homeautomation
spec:
  entryPoints:
    - web
    - websecure
    - haas
  routes:
    - match: Host(`homeassistant.tinker.haus`)
      kind: Rule
      services:
        - name: homeassistant
          port: 80
