apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
spec:
  headers:
    # contentSecurityPolicy: "default-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'; base-uri 'self';"
    browserXssFilter: true
    frameDeny: true