apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: traefik
  name: traefik-ingress-controller

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - name: traefik
        image: traefik:latest
        imagePullPolicy: Always
        args:
#            - --log.level=DEBUG
#            - --api.insecure
#            - --api.dashboard
#            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --entrypoints.influxdb.Address=:8086
            - --entrypoints.traefik.Address=:30002
            - --entrypoints.transmission.Address=:51413/udp
            - --providers.kubernetescrd
            - --certificatesResolvers.myresolver.acme.dnsChallenge.provider=namecheap
            - --certificatesResolvers.myresolver.acme.email=alex.sever.h@gmail.com
            - --certificatesResolvers.myresolver.acme.storage=/data/acme.json
#            - --providers.file.directory=/dynamicconf/
#            - --providers.file.watch=true
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 30002
          hostPort: 30002
        - containerPort: 8086
          hostPort: 8086
        - containerPort: 51413
          hostPort: 51413
          protocol: UDP
        env:
        - name: TZ
          value: "Europe/Bucharest"
        - name: NAMECHEAP_API_USER_FILE
          value: "/namecheap/user"
        - name: NAMECHEAP_API_KEY_FILE
          value: "/namecheap/key"
        volumeMounts:
        - name: namecheap-secret
          mountPath: /namecheap
          readOnly: true
        - mountPath: "/data"
          name: data
#        - mountPath: "/dynamicconf"
#          name: dynamicconf
      volumes:
      - name: namecheap-secret
        secret:
          secretName: namecheap-secret
      - name: data
        hostPath:
          path: /servers/traefik/data
          type: DirectoryOrCreate
      - name: dynamicconf
        hostPath:
          path: /servers/traefik/conf
          type: DirectoryOrCreate
