apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    globalArguments:
    - --global.checknewversion=false
    - --global.sendanonymoususage=false
    ports:
      e-web:
        port: 10080
        exposedPort: 10080
      websecure:
        port: 443
        exposedPort: 443
        tls:
          certResolver: letsencrypt
          domains:
            - main: "tinker.haus"
              sans:
                - "*.tinker.haus"
      e-websecure:
        port: 10443
        exposedPort: 10443
        tls:
          enabled: true
          certResolver: letsencrypt
          domains:
            - main: "tinker.haus"
              sans:
                - "*.tinker.haus"
      haas:
        port: 8123
        exposePort: 8123
      influxdb:
        port: 8086
        exposePort: 8086
      mariadb:
        port: 3306
        exposePort: 3306
      postgresql:
        port: 5432
        exposePort: 5432
    logs:
      general:
        level: INFO
    certificatesResolvers:
      letsencrypt:
        acme:
          dnsChallenge:
            provider: cloudflare
          storage: /datalocal/certs/acme.json
          email: "alex.sever.h@gmail.com"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            key: email
            name: cloudflare-api-credentials
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            key: apiKey
            name: cloudflare-api-credentials
    deployment:
      additionalVolumes:
        - name: datalocal
          hostPath:
            path: /srv/traefik/data/
    additionalVolumeMounts:
      - name: datalocal
        mountPath: "/datalocal"
    ingressRoute:
      dashboard:
        enabled: true
        # Custom match rule with host domain
        matchRule: Host(`traefik.tinker.haus`)
        entryPoints:
          - "web"
          - "websecure"