apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      e-web:
        port: 10080
        exposedPort: 10080
      websecure:
        port: 443
        exposedPort: 443
        tls:
          certResolver: letsencrypt
          domains:
            - main: "tinker.haus"
              sans:
                - "*.tinker.haus"
      e-websecure:
        port: 10443
        exposedPort: 10443
        tls:
          enabled: true
          certResolver: letsencrypt
          domains:
            - main: "tinker.haus"
              sans:
                - "*.tinker.haus"
      haas:
        port: 8123
        exposePort: 8123
      influxdb:
        port: 8086
        exposePort: 8086
      mariadb:
        port: 3306
        exposePort: 3306
      postgresql:
        port: 5432
        exposePort: 5432
    logs:
      general:
        level: DEBUG
    certResolvers:
      letsencrypt:
        dnsChallenge:
          provider: cloudflare
        storage: /datalocal/certs/acme.json
        email: "alex.sever.h@gmail.com"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            key: email
            name: cloudflare-api-credentials
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            key: apiKey
            name: cloudflare-api-credentials
    deployment:
      additionalVolumes:
        - name: datalocal
          hostPath:
            path: /srv/traefik/data/
    additionalVolumeMounts:
      - name: datalocal
        mountPath: "/datalocal"

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik-dashboard
spec:
  type: ClusterIP
  ports:
  - name: traefik
    port: 9000
    targetPort: traefik
    protocol: TCP
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress2
  namespace: kube-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`traefik.tinker.haus`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
      - name: traefik-dashboard
        port: 9000

