apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cron
  name: cron
  namespace: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: cron
        image: registry.tinker.haus/nextcloud
        imagePullPolicy: Always
        command: ["/cron.sh"]
        env:
        - name: MYSQL_HOST
          value: db
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_PASSWORD
          value: nextcloud
        - name: MYSQL_USER
          value: nextcloud
        - name: MYSQL_ROOT_PASSWORD
          value: nextcloud
        - name: REDIS_HOST
          value: redis
        volumeMounts:
        - name: nextcloud
          mountPath: /var/www/html
        - name: data
          mountPath: /data
        - name: cache
          mountPath: /cache
        - name: storage
          mountPath: /home-storage
      restartPolicy: Always
      volumes:
      - name: nextcloud
        hostPath:
          path: "/var/srv/nextcloud/html"
      - name: data
        hostPath:
          path: "/servers/nextcloud/data"
      - name: cache
        hostPath:
          path: "/var/srv/nextcloud/cache"
      - name: storage
        hostPath:
          path: "/home-storage"
