apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: preview-pre-generate
  name: preview-pre-generate
  namespace: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: preview-pre-generate
  template:
    metadata:
      labels:
        app: preview-pre-generate
    spec:
      containers:
      - name: preview-pre-generate
        image: registry.tinker.haus/nextcloud # nextcloud:fpm
        imagePullPolicy: Always
        command: ['sh', '-c', "echo '* * * * * /var/www/html/occ preview:pre-generate -vvvv' > /var/spool/cron/crontabs/www-data && /cron.sh"]
        env:
        - name: MYSQL_HOST
          value: db
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_PASSWORD
          value: nextcloud
        - name: MYSQL_USER
          value: nextcloud
        - name: MYSQL_ROOT_PASSWORD
          value: nextcloud
        - name: REDIS_HOST
          value: redis
        volumeMounts:
        - name: nextcloud
          mountPath: /var/www/html
        - name: data
          mountPath: /data
        - name: cache
          mountPath: /cache
        - name: storage
          mountPath: /home-storage
      restartPolicy: Always
      volumes:
      - name: nextcloud
        hostPath:
          path: "/var/srv/nextcloud/html"
      - name: data
        hostPath:
          path: "/servers/nextcloud/data"
      - name: cache
        hostPath:
          path: "/var/srv/nextcloud/cache"
      - name: storage
        hostPath:
          path: "/home-storage"
