apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: web-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: web-frontend
        image: docker-cache.tinker.haus/library/nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: PUID
          value: "2001"
        - name: PGID
          value: "2000"
        - name: TZ
          value: "Europe/Bucharest"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
        - name: nextcloud
          mountPath: /var/www/html
          readOnly: true
      volumes:
      - name: nginx-config
        hostPath:
          path: "/var/srv/nextcloud/nginx/nginx.conf"
          type: FileOrCreate
      - name: nextcloud
        hostPath:
          path: "/var/srv/nextcloud/html"

---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: nextcloud
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: web-frontend

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-web-frontend
  namespace: nextcloud
spec:
  entryPoints:
    - web
    - websecure
    - externalweb
    - externalwebsecure
  routes:
    - match: Host(`nextcloud.tinker.haus`)
      kind: Rule
      services:
        - name: web-frontend
          port: 80
      middlewares:
        - name: nextcloud-strict-transport-security@kubernetescrd
        - name: nextcloud-nextcloud-redirect@kubernetescrd

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirect
  namespace: nextcloud
spec:
  redirectRegex:
    regex: /.well-known/(card|cal)dav
    replacement: /remote.php/dav/

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strict-transport-security
  namespace: nextcloud
spec:
  headers:
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    referrerPolicy: no-referrer
