apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: registry.tinker.haus/tinkernextcloud # nextcloud:fpm
        imagePullPolicy: Always
        command: ["/usr/bin/ionice"]
        args: ["-c", "2", "-n", "2", "/entrypoint.sh", "php-fpm"]
        env:
        - name: MYSQL_HOST
          value: db
        - name: MYSQL_DATABASE
          value: nextcloud
        - name: MYSQL_PASSWORD
          value: nextcloud
        - name: MYSQL_USER
          value: nextcloud
        - name: MYSQL_ROOT_PASSWORD
          value: nextcloud
        - name: REDIS_HOST
          value: redis
        - name: NEXTCLOUD_DATA_DIR
          value: "/data"
        volumeMounts:
        - name: nextcloud
          mountPath: /var/www/html
        - name: data
          mountPath: /data
        - name: cache
          mountPath: /cache
      restartPolicy: Always
      volumes:
      - name: nextcloud
        hostPath:
          path: "/var/srv/nextcloud/html"
      - name: cache
        hostPath:
          path: "/var/srv/nextcloud/cache"
      - name: data
        hostPath:
          path: "/servers/nextcloud/data"

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: nextcloud
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: app
