apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collabora
  name: collabora
  namespace: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      containers:
      - name: collabora
        image: collabora/code:latest
        #imagePullPolicy: Always

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: collabora
  namespace: nextcloud
spec:
  ports:
    - port: 80
      targetPort: 9980
      protocol: TCP
  selector:
    app: collabora

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: collabora-ingressroute-auth
  namespace: nextcloud
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`office.tinker.haus`)
      kind: Rule
      services:
        - name: collabora
          port: 80
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
  tls:
    certResolver: myresolver
    domains:
    - main: "tinker.haus"
      sans:
      - "*.tinker.haus"
