apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: imaginary
  name: imaginary
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imaginary
  template:
    metadata:
      labels:
        app: imaginary
    spec:
      containers:
        - name: imaginary
          image: docker-cache.tinker.haus/nextcloud/aio-imaginary:latest
           # imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Bucharest
          ports:
            - containerPort: 9000
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: imaginary
  namespace: nextcloud
spec:
  ports:
    - port: 9000
  selector:
    app: imaginary
