apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirect
  namespace: nextcloud
spec:
  redirectRegex:
    regex: /.well-known/(card|cal)dav
    replacement: /remote.php/dav/
