apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authentik
  namespace: authentik
spec:
  repo: https://charts.goauthentik.io
  chart: authentik
  targetNamespace: authentik
  valuesContent: |-
    global:
      namespaceOverride: authentik
    authentik:
      secret_key: "%%AUTHENTIK_SECRET_KEY%%"
      error_reporting:
        enabled: false
      postgresql:
        host: postgresql.db
        user: authentik
        password: authentik
      email:
        host: "smtp.fastmail.com"
        port: 465
        username: "%%FASTMAIL_USERNAME%%"
        password: "%%FASTMAIL_API_KEY%%"
        # -- Enable either use_tls or use_ssl. They can't be enabled at the same time.
        use_tls: false
        use_ssl: true
        timeout: 30
        from: "authentik@tinker.haus"
    redis:
      enabled: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
spec:
  entryPoints:
    - web
    - websecure
    - e-web
    - e-websecure
  routes:
    - match: Host(`authentik.tinker.haus`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
      middlewares:
        - name: crowdsec-bouncer@kubernetescrd
        - name: authentik-strict-transport-security@kubernetescrd

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strict-transport-security
  namespace: authentik
spec:
  headers:
    # Strict-Transport-Security
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customResponseHeaders:
      # Content-Security-Policy
      #Content-Security-Policy: "default-src 'self'; script-src 'self' https://authentik.tinker.haus; object-src 'none';"
      Content-Security-Policy: "default-src 'self' http: https: data: blob: 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval';"
      # X-Content-Type-Options
      X-Content-Type-Options: "nosniff"
      # Referrer-Policy
      Referrer-Policy: "no-referrer-when-downgrade"
      # Permissions-Policy
      Permissions-Policy: "geolocation=(), microphone=(), camera=(), fullscreen=(self)"
      # The anti-clickjacking X-Frame-Options header
      X-Frame-Options: "SAMEORIGIN"