apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authentik
  namespace: authentik
spec:
  repo: https://charts.goauthentik.io
  chart: authentik
  targetNamespace: authentik
  valuesContent: |-
    global:
      namespaceOverride: authentik
    authentik:
      secret_key: "%%AUTHENTIK_SECRET_KEY%%"
      error_reporting:
        enabled: false
      postgresql:
        host: postgresql.db
        user: authentik
        password: authentik
      email:
        host: "smtp.fastmail.com"
        port: 465
        username: "%%FASTMAIL_USERNAME%%"
        password: "%%FASTMAIL_API_KEY%%"
        # -- Enable either use_tls or use_ssl. They can't be enabled at the same time.
        use_tls: false
        use_ssl: true
        timeout: 30
        from: "authentik@tinker.haus"
    server:
      ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
          - authentik.tinker.haus
    redis:
      enabled: true

# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: authentik
#   namespace: authentik
# spec:
#   entryPoints:
#     - web
#     - websecure
#   routes:
#     - match: Host(`authentik.tinker.haus`)
#       kind: Rule
#       services:
#         - name: authentik-server
#           port: 80
