apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitweb
  namespace: services
spec:
  selector:
    matchLabels:
      app: gitweb
  replicas: 1
  template:
    metadata:
      labels:
        app: gitweb
    spec:
      containers:
      - name: gitweb
        image: docker-cache.tinker.haus/fraoustin/gitweb
         # imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: CONTAINER_TIMEZONE
          value: "Europe/Bucharest"
        - name: GITUSER
          value: "gituser"
        - name: GITPASSWORD
          value: "gitpassword"
        volumeMounts:
          - name: repos
            mountPath: /var/lib/git
      volumes:
        - name: repos
          hostPath:
            path: /srv/services/git
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: gitweb
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: gitweb

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitweb
  namespace: services
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`gitweb.tinker.haus`)
      kind: Rule
      services:
        - name: gitweb
          port: 80

