apiVersion: apps/v1
kind: Deployment
metadata:
  name: nut-http
  namespace: services
spec:
  selector:
    matchLabels:
      app: nut-http
  replicas: 1
  template:
    metadata:
      labels:
        app: nut-http
    spec:
      containers:
      - name: nut-http
        image: docker-cache.tinker.haus/deetoreu/nut-http
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
          - name: NUT_ADDRESS
            value: "10.1.1.42"

---
apiVersion: v1
kind: Service
metadata:
  name: nut-http
  namespace: services
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  type: NodePort
  selector:
    app: nut-http

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nut-http-ingressroute-notls
  namespace: services
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nut.tinker.haus`)
      kind: Rule
      services:
        - name: nut-http
          port: 3001
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
