apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: services
spec:
  selector:
    matchLabels:
      app: searxng
  replicas: 1
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
      - name: searxng
        image: docker-cache.tinker.haus/searxng/searxng
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: INSTANCE_NAME
          value: "tinker.haus"
        - name: BASE_URL
          value: "http://searxng.tinker.haus"
        volumeMounts:
          - name: repos
            mountPath: /etc/searxng
      volumes:
        - name: repos
          hostPath:
            path: /var/srv/services/searxng
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    app: searxng

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng
  namespace: services
spec:
  entryPoints:
    - web
    - websecure
    - externalweb
    - externalwebsecure
  routes:
    - match: Host(`searxng.tinker.haus`)
      kind: Rule
      services:
        - name: searxng
          port: 80
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
        - name: default-redirect-to-https@kubernetescrd
