apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasmota
  namespace: services
spec:
  selector:
    matchLabels:
      app: tasmota
  replicas: 1
  template:
    metadata:
      labels:
        app: tasmota
    spec:
      containers:
      - name: tasmota
        image: registry.tinker.haus/pushgetserver
        imagePullPolicy: Always
        workingDir: /tasmota
        ports:
        - name: main
          containerPort: 8000
        volumeMounts:
          - name: tasmota
            mountPath: /tasmota
      volumes:
        - name: tasmota
          hostPath:
            path: /servers/tasmota
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: tasmota
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  type: NodePort
  selector:
    app: tasmota

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tasmota-ingressroute-auth
  namespace: services
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`tasmota.tinker.haus`)
      kind: Rule
      services:
        - name: tasmota
          port: 80
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
