apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: services
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: docker-cache.tinker.haus/library/telegraf
        imagePullPolicy: Always
        args: ["--debug"]
        securityContext:
          privileged: true
          capabilities:
            add: ["SETFCAP"]
        env:
          - name: HOST_ETC
            value: "/hostfs/etc"
          - name: HOST_PROC
            value: "/hostfs/proc"
          - name: HOST_SYS
            value: "/hostfs/sys"
          - name: HOST_VAR
            value: "/hostfs/var"
          - name: HOST_RUN
            value: "/hostfs/run"
          - name: HOST_MOUNT_PREFIX
            value: "/hostfs"
        volumeMounts:
          - name: conf
            mountPath: /etc/telegraf/telegraf.conf
          - name: hostfs
            mountPath: /hostfs
            readOnly: true
      volumes:
        - name: conf
          hostPath:
            path: /var/srv/homeautomation/telegraf/telegraf.conf
            type: FileOrCreate
        - name: hostfs
          hostPath:
            path: /
            type: Directory
