apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitweb
  namespace: services
spec:
  selector:
    matchLabels:
      app: gitweb
  replicas: 1
  template:
    metadata:
      labels:
        app: gitweb
    spec:
      containers:
      - name: gitweb
        image: fraoustin/gitweb
        #imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: CONTAINER_TIMEZONE
          value: "Europe/Bucharest"
#        - name: IHM
#          value: "mdl"
        - name: GITUSER
          value: "gituser"
        - name: GITPASSWORD
          value: "gitpassword"
        volumeMounts:
          - name: repos
            mountPath: /var/lib/git
      volumes:
        - name: repos
          hostPath:
            path: /git
            type: DirectoryOrCreate


---
apiVersion: v1
kind: Service
metadata:
  name: gitweb
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: gitweb
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitweb-ingressroute-auth
  namespace: services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitweb.tinker.haus`)
      kind: Rule
      services:
        - name: gitweb
          port: 80
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
  tls:
    certResolver: myresolver
    domains:
    - main: "tinker.haus"
      sans:
      - "*.tinker.haus"
