apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: services
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
      annotations:
        container.apparmor.security.beta.kubernetes.io/jenkins: unconfined 
    spec:
      containers:
      - name: jenkins
        image: registry.tinker.haus/tinkerjenkins:centos # jenkins/jenkins:centos
        imagePullPolicy: Always
        ports:
        - name: webui
          containerPort: 8080
        - name: slaves
          containerPort: 50000
        env:
          - name: TZ
            value: "Europe/Bucharest"
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: artefacts
            mountPath: /artefacts
        livenessProbe:
          httpGet:
            path: /login
            port: webui
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
        - name: jenkins-home
          hostPath:
            path: /servers/jenkins/home
            type: DirectoryOrCreate
        - name: artefacts
          hostPath:
            path: /storage/artefacts
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    app: jenkins
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ingressroute-auth
  namespace: services
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kenjins.tinker.haus`)
      kind: Rule
      services:
        - name: jenkins
          port: 80
      middlewares:
        - name: default-ip-whitelist-plus-github-local@kubernetescrd
        - name: services-strict-transport-security@kubernetescrd
#        - name: redirect-redirect-to-https@kubernetescrd
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ingressroute-auth-tls
  namespace: services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kenjins.tinker.haus`)
      kind: Rule
      services:
        - name: jenkins
          port: 80
      middlewares:
        - name: default-ip-whitelist-plus-github-local@kubernetescrd
        - name: services-strict-transport-security@kubernetescrd
#        - name: redirect-redirect-to-https@kubernetescrd
  tls:
    certResolver: myresolver
    domains:
    - main: "tinker.haus"
      sans:
      - "*.tinker.haus"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strict-transport-security
  namespace: services
spec:
  headers:
    sslRedirect: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
