apiVersion: apps/v1
kind: Deployment
metadata:
  name: omada-controller
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omada-controller
  template:
    metadata:
      labels:
        app: omada-controller
    spec:
      #hostNetwork: true
      containers:
        - name: omada-controller
          image: mbentley/omada-controller:latest
          env:
            - name: PUID
              value: "508"
            - name: PGID
              value: "508"
            - name: MANAGE_HTTP_PORT
              value: "8088"
            - name: MANAGE_HTTPS_PORT
              value: "8043"
            - name: PORTAL_HTTP_PORT
              value: "8088"
            - name: PORTAL_HTTPS_PORT
              value: "8844"
            - name: PORT_APP_DISCOVERY
              value: "27001"
            - name: PORT_ADOPT_V1
              value: "29812"
            - name: PORT_UPGRADE_V1
              value: "29813"
            - name: PORT_MANAGER_V1
              value: "29811"
            - name: PORT_MANAGER_V2
              value: "29814"
            - name: PORT_DISCOVERY
              value: "29810"
            - name: PORT_TRANSFER_V2
              value: "29815"
            - name: PORT_RTTY
              value: "29816"
            - name: SHOW_SERVER_LOGS
              value: "true"
            - name: SHOW_MONGODB_LOGS
              value: "false"
            - name: SSL_CERT_NAME
              value: "tls.crt"
            - name: SSL_KEY_NAME
              value: "tls.key"
            - name: TZ
              value: "Europe/Bucharest"
          volumeMounts:
            - name: omada-data
              mountPath: /opt/tplink/EAPController/data
            - name: omada-logs
              mountPath: /opt/tplink/EAPController/logs
          securityContext:
            capabilities:
              add: ["SYS_RESOURCE"] # Required to change ulimits
          resources: {} # Ensure no invalid entries
      volumes:
        - name: omada-data
          hostPath:
            type: DirectoryOrCreate
            path: /srv/services/omada/data
        - name: omada-logs
          hostPath:
            type: DirectoryOrCreate
            path: /srv/services/omada/logs

---
apiVersion: v1
kind: Service
metadata:
  name: omada-controller
  namespace: services
spec:
  type: LoadBalancer
  #loadBalancerIP: 192.168.100.83 # Static IP assigned by MetalLB
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: https
      protocol: TCP
      port: 8043
      targetPort: 8043
    - name: app-discovery
      protocol: TCP
      port: 27001
      targetPort: 27001
    - name: udp-management
      protocol: UDP
      port: 19810
      targetPort: 19810
    - name: udp-discovery
      protocol: UDP
      port: 29810
      targetPort: 29810
    - name: tcp-manager-v1
      protocol: TCP
      port: 29811
      targetPort: 29811
    - name: tcp-adopt-v1
      protocol: TCP
      port: 29812
      targetPort: 29812
    - name: tcp-upgrade-v1
      protocol: TCP
      port: 29813
      targetPort: 29813
    - name: tcp-manager-v2
      protocol: TCP
      port: 29814
      targetPort: 29814
    - name: tcp-transfer-v2
      protocol: TCP
      port: 29815
      targetPort: 29815
    - name: tcp-rtty
      protocol: TCP
      port: 29816
      targetPort: 29816
  selector:
    app: omada-controller


---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omada-controller
  namespace: services
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`omada.tinker.haus`)
      kind: Rule
      services:
        - name: omada-controller
          port: 8088
