apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: services
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        #imagePullPolicy: Always
        ports:
        - name: main
          containerPort: 5000
        volumeMounts:
          - name: registry
            mountPath: /var/lib/registry
      volumes:
        - name: registry
          hostPath:
            path: /servers/registry
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: NodePort
  selector:
    app: registry

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: registry-ingressroute-auth
  namespace: services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`registry.tinker.haus`)
      kind: Rule
      services:
        - name: registry
          port: 80
      middlewares:
        - name: default-ip-whitelist-local@kubernetescrd
  tls:
    certResolver: myresolver
    domains:
    - main: "tinker.haus"
      sans:
      - "*.tinker.haus"
