apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strict-transport-security
  namespace: services
spec:
  headers:
    sslRedirect: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
