apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: services
spec:
  selector:
    matchLabels:
      app: whoami
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: docker-cache.tinker.haus/traefik/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: whoami

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: services
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`whoami.tinker.haus`)
      kind: Rule
      services:
        - name: whoami
          port: 80
      middlewares:
        - name: crowdsec-bouncer@kubernetescrd