apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: db
spec:
  serviceName: influxdb
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: docker-cache.tinker.haus/library/influxdb:latest
         # imagePullPolicy: Always
        ports:
        - containerPort: 8086
          protocol: TCP
        env:
          []
        volumeMounts:
          - name: influxdb2
            mountPath: /var/lib/influxdb2
      volumes:
        - name: influxdb2
          hostPath:
            path: /srv/db/influxdb2
            type: DirectoryOrCreate


---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: db
spec:
  ports:
  - name: "influxdbtcp"
    port: 8086
    protocol: TCP
    targetPort: 8086
  type: NodePort
  selector:
    app: influxdb

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb
  namespace: db
spec:
  entryPoints:
    - web
    - websecure
    - influxdb
  routes:
    - match: Host(`influxdb.tinker.haus`)
      kind: Rule
      services:
        - name: influxdb
          port: 8086
      middlewares:
        - name: default-redirect-to-https@kubernetescrd
