apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: db
spec:
  serviceName: mariadb
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: docker-cache.tinker.haus/library/mariadb
        imagePullPolicy: Always
        args: ["--innodb-read-only-compressed=OFF"]
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
          []
        volumeMounts:
        - name: mariadb
          mountPath: /var/lib/mysql
      - name: phpmyadmin
        image: docker-cache.tinker.haus/library/phpmyadmin
        imagePullPolicy: Always
        env:
          - name:  PMA_HOST
            value: "mariadb"
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: mariadb
        hostPath:                                                                           
          path: "/var/srv/db/mariadb"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mariadb
    - port: 80
      targetPort: 80
      protocol: TCP
      name: phpmyadmin
  selector:
    app: mariadb

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mariadb
  namespace: db
spec:
  entryPoints:
    - mariadb
  routes:
  - match: HostSNI(`*`)
    services:
    - name: mariadb
      port: 3306

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: phpmyadmin
  namespace: db
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`phpmyadmin.tinker.haus`)
      kind: Rule
      services:
        - name: mariadb
          port: 80
      middlewares:
        - name: default-redirect-to-https@kubernetescrd
