apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:jdk11
        #imagePullPolicy: Always
        ports:
        - name: webui
          containerPort: 8080
        - name: slaves
          containerPort: 50000
        env:
          - name: TZ
            value: "Europe/Bucharest"
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: storage
            mountPath: /jenkins
        livenessProbe:
          httpGet:
            path: /login
            port: webui
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 15
      volumes:
        - name: jenkins-home
          hostPath:
            path: /var/srv/services/jenkins
            type: DirectoryOrCreate
        - name: storage
          hostPath:
            path: /jenkins
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: webinterface
  - port: 50000
    protocol: TCP
    targetPort: 50000
    name: slaveport
  type: NodePort
  selector:
    app: jenkins
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ingressroute-auth
  namespace: jenkins
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kenjins.tinker.haus`)
      kind: Rule
      services:
        - name: jenkins
          port: 80
      middlewares:
        - name: default-ip-whitelist-plus-github-local@kubernetescrd
        - name: jenkins-strict-transport-security@kubernetescrd
        - name: redirect-redirect-to-https@kubernetescrd
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ingressroute-auth-tls
  namespace: jenkins
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kenjins.tinker.haus`)
      kind: Rule
      services:
        - name: jenkins
          port: 80
      middlewares:
        - name: default-ip-whitelist-plus-github-local@kubernetescrd
        - name: jenkins-strict-transport-security@kubernetescrd
        - name: redirect-redirect-to-https@kubernetescrd
  tls:
    certResolver: myresolver
    domains:
    - main: "tinker.haus"
      sans:
      - "*.tinker.haus"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strict-transport-security
  namespace: jenkins
spec:
  headers:
    sslRedirect: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
