apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webui
  template:
    metadata:
      labels:
        name: webui
    spec:
      volumes:
      - hostPath:
          path: /srv/ollama/webui
          type: DirectoryOrCreate
        name: webui-storage
      containers:
        - name: webui
          image: ghcr.io/open-webui/open-webui:main
          volumeMounts:
          - mountPath: /app/backend/data
            name: webui-storage
          env:
            - name: OLLAMA_BASE_URLS
              value: "http://ollama"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: ollama
spec:
  type: NodePort
  selector:
    name: webui
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ollama-web-frontend
  namespace: ollama
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ollama.tinker.haus`)
      kind: Rule
      services:
        - name: webui
          port: 80


