apiVersion: v1
kind: Namespace
metadata:
  name: redirect

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-redirect
  namespace: redirect
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`{host:^[^m][a-z-.]+$}`)
      kind: Rule
      services:
        - name: noop
          port: 80
      middlewares:
        - name: redirect-to-https

---
apiVersion: v1
kind: Service
metadata:
  name: noop
  namespace: redirect
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    app: noop

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noop
  namespace: redirect
spec:
  selector:
    matchLabels:
      app: noop
  replicas: 1
  template:
    metadata:
      labels:
        app: noop
    spec:
      containers:
      - name: noop
        image: nginx:latest
        ports:
        - containerPort: 8080
